//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionCliente
    {
        public string Codigo { get; set; }
        public Nullable<int> PaisResidenciaId { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> PaisTelefonoId { get; set; }
        public string TipoDocumentoId { get; set; }
        public Nullable<int> PaisExpedicionDocumentoId { get; set; }
        public string LugarEmisionDocumento { get; set; }
        public Nullable<System.DateTime> FechaEmisionDocumento { get; set; }
        public Nullable<System.DateTime> FechaCaducidadDocumento { get; set; }
        public string SituacionLaboralId { get; set; }
        public string SectorIndustriaId { get; set; }
        public Nullable<int> PaisNacimientoId { get; set; }
        public Nullable<int> PaisNacionalidadId { get; set; }
        public string SexoId { get; set; }
        public string DepartamentoId { get; set; }
        public string ProvinciaId { get; set; }
        public string DistritoId { get; set; }
        public string CodigoCiudad { get; set; }
        public string Email { get; set; }
        public string Postal { get; set; }
        public string Telefono { get; set; }
    }
}
