//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class activoc
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> feinco { get; set; }
        public string clase { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public string agencia { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string enuso { get; set; }
        public Nullable<System.DateTime> fechauso { get; set; }
    
        public virtual agencia agencia1 { get; set; }
        public virtual clas clas { get; set; }
    }
}
