//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class activod
    {
        public string codigo { get; set; }
        public int numero { get; set; }
        public string operacion { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string entidad { get; set; }
        public string factura { get; set; }
        public string guia { get; set; }
        public string moneda { get; set; }
        public string imporsol { get; set; }
        public string ticambio { get; set; }
        public string caja { get; set; }
        public string oripa { get; set; }
        public string cuenta { get; set; }
        public string movim { get; set; }
        public string documento { get; set; }
        public string referen { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechabco { get; set; }
        public string lotecon { get; set; }
        public string tipdo { get; set; }
        public string comprobante { get; set; }
        public string tipocom { get; set; }
        public string rubro { get; set; }
        public string lote { get; set; }
        public string origen { get; set; }
    
        public virtual caja caja1 { get; set; }
        public virtual bcocuenta bcocuenta { get; set; }
        public virtual cajavario cajavario { get; set; }
        public virtual moneda moneda1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
