//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class acumulado
    {
        public string cliente { get; set; }
        public int numero { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public string agencia { get; set; }
        public string comentariou { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string unicas { get; set; }
        public string cada { get; set; }
        public string multiples { get; set; }
        public string pais { get; set; }
        public string reci { get; set; }
        public string envi { get; set; }
        public string cheq { get; set; }
        public string trav { get; set; }
        public string cove { get; set; }
        public string imreci { get; set; }
        public string imenvi { get; set; }
        public string imcheq { get; set; }
        public string imtrav { get; set; }
        public string imcove { get; set; }
        public string comentarioc { get; set; }
        public Nullable<System.DateTime> fechac { get; set; }
        public string horac { get; set; }
        public string usuarioc { get; set; }
        public string anulado { get; set; }
    }
}
