//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class adenda
    {
        public string contrato { get; set; }
        public int adenda1 { get; set; }
        public string cliente { get; set; }
        public string carabon { get; set; }
        public string importe { get; set; }
        public string cartera { get; set; }
        public string interes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
    }
}
