//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class adipersonal
    {
        public string codigo { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string paisnacio { get; set; }
        public string paispasa { get; set; }
        public string larga { get; set; }
        public string telefono { get; set; }
        public string tipovia1 { get; set; }
        public string nombrevia1 { get; set; }
        public string numvia1 { get; set; }
        public string departa1 { get; set; }
        public string interior1 { get; set; }
        public string manzana1 { get; set; }
        public string lote1 { get; set; }
        public string kilometro1 { get; set; }
        public string block1 { get; set; }
        public string etapa1 { get; set; }
        public string tipozona1 { get; set; }
        public string nombrezona1 { get; set; }
        public string referencia1 { get; set; }
        public string ubigeo1 { get; set; }
        public string tipovia2 { get; set; }
        public string nombrevia2 { get; set; }
        public string numvia2 { get; set; }
        public string departa2 { get; set; }
        public string interior2 { get; set; }
        public string manzana2 { get; set; }
        public string lote2 { get; set; }
        public string kilometro2 { get; set; }
        public string block2 { get; set; }
        public string etapa2 { get; set; }
        public string tipozona2 { get; set; }
        public string nombrezona2 { get; set; }
        public string referencia2 { get; set; }
        public string ubigeo2 { get; set; }
        public string centroslud { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
