//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenban
    {
        public string agencia { get; set; }
        public string entidad { get; set; }
        public string maestra { get; set; }
        public string ctaagen { get; set; }
        public string sobregiro { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string modelo { get; set; }
        public string prefijo { get; set; }
    }
}
