//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class agencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agencia()
        {
            this.activocs = new HashSet<activoc>();
            this.cajamovimcs = new HashSet<cajamovimc>();
            this.clientes = new HashSet<cliente>();
            this.comisagens = new HashSet<comisagen>();
            this.envios = new HashSet<envio>();
            this.nacionals = new HashSet<nacional>();
            this.bcomovims = new HashSet<bcomovim>();
            this.cajamovimcs1 = new HashSet<cajamovimc>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string contacto1 { get; set; }
        public string contacto2 { get; set; }
        public string liquiefec { get; set; }
        public string liquicheq { get; set; }
        public string taricheq { get; set; }
        public Nullable<int> numlote { get; set; }
        public string codmg { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fondodol { get; set; }
        public string fondosol { get; set; }
        public string saldodol { get; set; }
        public string saldosol { get; set; }
        public string cajaprin { get; set; }
        public string sistema { get; set; }
        public string propia { get; set; }
        public string codunit { get; set; }
        public string departamento { get; set; }
        public Nullable<int> vouchers { get; set; }
        public Nullable<int> comproban { get; set; }
        public string ruc { get; set; }
        public string serie { get; set; }
        public Nullable<int> boleta { get; set; }
        public Nullable<int> factura { get; set; }
        public Nullable<int> credito { get; set; }
        public string locka { get; set; }
        public string factor { get; set; }
        public string razon { get; set; }
        public string estado { get; set; }
        public string interbank { get; set; }
        public string topeinter { get; set; }
        public string ubigeo { get; set; }
        public string admin { get; set; }
        public string ventas { get; set; }
        public string impresora { get; set; }
        public string establecim { get; set; }
        public string serienc { get; set; }
        public Nullable<int> secuencia { get; set; }
        public Nullable<int> rollo { get; set; }
        public Nullable<int> lotebol { get; set; }
        public Nullable<int> lotefac { get; set; }
        public Nullable<int> lotenc { get; set; }
        public string ciudad { get; set; }
        public string postal { get; set; }
        public string globokas { get; set; }
        public string nacional { get; set; }
        public string riesgo { get; set; }
        public Nullable<System.DateTime> fechaesta { get; set; }
        public string desde1 { get; set; }
        public string hasta1 { get; set; }
        public string desde2 { get; set; }
        public string hasta2 { get; set; }
        public string desde3 { get; set; }
        public string hasta3 { get; set; }
        public string tcc { get; set; }
        public string topeenvios { get; set; }
        public string grupo { get; set; }
        public Nullable<int> credito2 { get; set; }
        public string fedex { get; set; }
        public string orbis { get; set; }
        public string codvigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activoc> activocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovimc> cajamovimcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente> clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comisagen> comisagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<envio> envios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nacional> nacionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovimc> cajamovimcs1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
