//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion
    {
        public string personal { get; set; }
        public int secuencia { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string tipo { get; set; }
        public string agencia { get; set; }
        public Nullable<int> diadesde { get; set; }
        public Nullable<int> diahasta { get; set; }
        public string ingreso { get; set; }
        public string salida { get; set; }
        public string usua { get; set; }
        public string referencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public string refrige { get; set; }
        public string sobretpo { get; set; }
        public string agencia2 { get; set; }
        public Nullable<int> diadesde2 { get; set; }
        public Nullable<int> diahasta2 { get; set; }
        public string ingreso2 { get; set; }
        public string salida2 { get; set; }
        public string usua2 { get; set; }
        public string refrige2 { get; set; }
        public string sobretpo2 { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
