//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcocuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bcocuenta()
        {
            this.activods = new HashSet<activod>();
            this.envios = new HashSet<envio>();
            this.bcomovims = new HashSet<bcomovim>();
            this.centros = new HashSet<centro>();
            this.bcomovims1 = new HashSet<bcomovim>();
            this.cajamovimcs = new HashSet<cajamovimc>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string banco { get; set; }
        public string tipo { get; set; }
        public string moneda { get; set; }
        public string autoriza1 { get; set; }
        public string autoriza2 { get; set; }
        public string autoriza3 { get; set; }
        public string autoriza4 { get; set; }
        public string autoriza5 { get; set; }
        public string clave { get; set; }
        public string saldo { get; set; }
        public string sobregiro { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> correlativo { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string locka { get; set; }
        public string contable { get; set; }
        public string saldodol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activod> activods { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual usuario usuario3 { get; set; }
        public virtual usuario usuario4 { get; set; }
        public virtual usuario usuario5 { get; set; }
        public virtual bcorefer bcorefer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<envio> envios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<centro> centros { get; set; }
        public virtual moneda moneda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovimc> cajamovimcs { get; set; }
        public virtual usuario usuario6 { get; set; }
    }
}
