//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcocomi
    {
        public string banco { get; set; }
        public string comision { get; set; }
        public string moneda { get; set; }
        public string hasta1 { get; set; }
        public string porcen1 { get; set; }
        public string minimo1 { get; set; }
        public string hasta2 { get; set; }
        public string porcen2 { get; set; }
        public string minimo2 { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual bcorefer bcorefer { get; set; }
        public virtual bcooperac bcooperac { get; set; }
        public virtual moneda moneda1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
