//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcomovim
    {
        public string cuenta { get; set; }
        public string numero { get; set; }
        public string banco { get; set; }
        public string tipo { get; set; }
        public string moneda { get; set; }
        public string operacion { get; set; }
        public string carabon { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string importe { get; set; }
        public string transito { get; set; }
        public string autoriza { get; set; }
        public string tipodoc { get; set; }
        public string cheque { get; set; }
        public string ticambio { get; set; }
        public string codcomis { get; set; }
        public string comision { get; set; }
        public string oridesti { get; set; }
        public string odcuenta { get; set; }
        public string odcaja { get; set; }
        public string odopera { get; set; }
        public string oddocum { get; set; }
        public string odcentro { get; set; }
        public string odvarios { get; set; }
        public string odagencia { get; set; }
        public string cobrado { get; set; }
        public string referen { get; set; }
        public string otros { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public Nullable<int> cierre { get; set; }
        public string rubro { get; set; }
        public string lotecon { get; set; }
        public string tipdo { get; set; }
        public string tipago { get; set; }
        public string operacon { get; set; }
        public string giro { get; set; }
        public string tipocom { get; set; }
        public string agenciagas { get; set; }
        public string comisionn { get; set; }
        public string princom { get; set; }
        public string dolares { get; set; }
        public string spotnumeron { get; set; }
        public string diferencia { get; set; }
        public string cambiohis { get; set; }
        public Nullable<System.DateTime> fechaliq { get; set; }
    
        public virtual agencia agencia { get; set; }
        public virtual bcocuenta bcocuenta { get; set; }
        public virtual bcocuenta bcocuenta1 { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual bcorefer bcorefer { get; set; }
        public virtual moneda moneda1 { get; set; }
        public virtual caja caja { get; set; }
        public virtual centro centro { get; set; }
        public virtual cajavario cajavario { get; set; }
        public virtual bcooperac bcooperac { get; set; }
        public virtual usuario usuario2 { get; set; }
    }
}
