//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcooperac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bcooperac()
        {
            this.bcocomis = new HashSet<bcocomi>();
            this.bcomovims = new HashSet<bcomovim>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string carabon { get; set; }
        public Nullable<int> registrar { get; set; }
        public Nullable<int> autoriza { get; set; }
        public Nullable<int> cheque { get; set; }
        public Nullable<int> transito { get; set; }
        public Nullable<int> ticambio { get; set; }
        public Nullable<int> comision { get; set; }
        public Nullable<int> orides { get; set; }
        public Nullable<int> referencia { get; set; }
        public Nullable<int> caja { get; set; }
        public Nullable<int> operacion { get; set; }
        public Nullable<int> corresponsal { get; set; }
        public Nullable<int> varios { get; set; }
        public Nullable<int> agencia { get; set; }
        public Nullable<int> afectaod { get; set; }
        public Nullable<int> documento { get; set; }
        public string opercomis { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipodoc { get; set; }
        public string contable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcocomi> bcocomis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
