//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajavario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajavario()
        {
            this.activods = new HashSet<activod>();
            this.bcomovims = new HashSet<bcomovim>();
            this.carteras = new HashSet<cartera>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string abrevia { get; set; }
        public string direccion { get; set; }
        public string clase { get; set; }
        public string contacto1 { get; set; }
        public string contacto2 { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha1 { get; set; }
        public string locka { get; set; }
        public Nullable<int> numcartera { get; set; }
        public string saldo { get; set; }
        public string sobregiro { get; set; }
        public string saldonac { get; set; }
        public string sobregironac { get; set; }
        public string reserva { get; set; }
        public string tarifa { get; set; }
        public string comision { get; set; }
        public string estado { get; set; }
        public string relacionada { get; set; }
        public string tarifanac { get; set; }
        public string clave { get; set; }
        public string saldoeuro { get; set; }
        public string inafecto { get; set; }
        public string largo { get; set; }
        public string saldol { get; set; }
        public string saldonacl { get; set; }
        public string corto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activod> activods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartera> carteras { get; set; }
        public virtual personal personal { get; set; }
    }
}
