//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajaoper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cajaoper()
        {
            this.cajamovimcs = new HashSet<cajamovimc>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string abrevia { get; set; }
        public string ingsal { get; set; }
        public Nullable<int> registrar { get; set; }
        public Nullable<int> efectivo { get; set; }
        public Nullable<int> deposito { get; set; }
        public Nullable<int> cheque { get; set; }
        public Nullable<int> travel { get; set; }
        public Nullable<int> dolares { get; set; }
        public Nullable<int> nacional { get; set; }
        public Nullable<int> monedae { get; set; }
        public Nullable<int> transito { get; set; }
        public Nullable<int> ticambio { get; set; }
        public Nullable<int> capital { get; set; }
        public Nullable<int> orides { get; set; }
        public Nullable<int> cuenta { get; set; }
        public Nullable<int> caja { get; set; }
        public Nullable<int> corresponsal { get; set; }
        public Nullable<int> agencia { get; set; }
        public Nullable<int> varios { get; set; }
        public Nullable<int> afectaod { get; set; }
        public Nullable<int> codopera { get; set; }
        public Nullable<int> documento { get; set; }
        public string operacion { get; set; }
        public string tipodoc { get; set; }
        public Nullable<int> enviaag { get; set; }
        public Nullable<int> sumariza { get; set; }
        public string contable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovimc> cajamovimcs { get; set; }
    }
}
