//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajacierre
    {
        public string caja { get; set; }
        public int numero { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaini { get; set; }
        public string horaini { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string horafin { get; set; }
        public string estado { get; set; }
    
        public virtual caja caja1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
