//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajasaldo
    {
        public string caja { get; set; }
        public string moneda { get; set; }
        public string saldoefe { get; set; }
        public string saldoche { get; set; }
        public string saldotra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string transefe { get; set; }
        public string transche { get; set; }
        public string transtra { get; set; }
    
        public virtual caja caja1 { get; set; }
        public virtual moneda moneda1 { get; set; }
    }
}
