//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajamovimc
    {
        public string caja { get; set; }
        public string numero { get; set; }
        public string lote { get; set; }
        public Nullable<int> cierre { get; set; }
        public string tipo { get; set; }
        public string agencia { get; set; }
        public string operacion { get; set; }
        public string ingsal { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string princom { get; set; }
        public string transito { get; set; }
        public string oridesti { get; set; }
        public string odcuenta { get; set; }
        public string odopera { get; set; }
        public string odcaja { get; set; }
        public string odcentro { get; set; }
        public string odcliente { get; set; }
        public string odvarios { get; set; }
        public string odagencia { get; set; }
        public string oddocum { get; set; }
        public string odlote { get; set; }
        public string numerod { get; set; }
        public string estado { get; set; }
        public string ticambio { get; set; }
        public string referen { get; set; }
        public string otros { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string rubro { get; set; }
        public string lotecon { get; set; }
        public string tipodoc { get; set; }
        public string operacon { get; set; }
        public string giro { get; set; }
        public string tipocom { get; set; }
        public string agenciagas { get; set; }
    
        public virtual agencia agencia1 { get; set; }
        public virtual agencia agencia2 { get; set; }
        public virtual bcocuenta bcocuenta { get; set; }
        public virtual caja caja1 { get; set; }
        public virtual caja caja2 { get; set; }
        public virtual centro centro { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual cajaoper cajaoper { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
