//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cajamovimd
    {
        public string caja { get; set; }
        public string numero { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
    
        public virtual caja caja1 { get; set; }
        public virtual moneda moneda1 { get; set; }
    }
}
