//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendario
    {
        public string ano { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> dia { get; set; }
        public string feriado { get; set; }
        public string calculado { get; set; }
        public string utilidad { get; set; }
    }
}
