//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartera
    {
        public string codigo { get; set; }
        public string numero { get; set; }
        public string numcarabo { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string carabon { get; set; }
        public string importe { get; set; }
        public string cajabanco { get; set; }
        public string codigocb { get; set; }
        public Nullable<int> cierre { get; set; }
        public string operacion { get; set; }
        public string movimcb { get; set; }
        public string tipobco { get; set; }
        public string documento { get; set; }
        public string referen { get; set; }
        public string interes { get; set; }
        public Nullable<System.DateTime> fechainter { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public string moneda { get; set; }
        public string operacon { get; set; }
        public string giro { get; set; }
        public string lotecon { get; set; }
        public string tipotar { get; set; }
        public string cliente { get; set; }
        public string tarifa { get; set; }
        public string comision { get; set; }
        public string numtar { get; set; }
        public string concepto { get; set; }
        public string largo { get; set; }
    
        public virtual cajavario cajavario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
