//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        public int numero { get; set; }
        public Nullable<System.DateTime> pagosdesde { get; set; }
        public Nullable<System.DateTime> pagoshasta { get; set; }
        public Nullable<int> pagoscanti { get; set; }
        public Nullable<System.DateTime> enviosdesde { get; set; }
        public Nullable<System.DateTime> envioshasta { get; set; }
        public Nullable<int> envioscanti { get; set; }
    }
}
