//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class centro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public centro()
        {
            this.bcomovims = new HashSet<bcomovim>();
            this.cajamovimcs = new HashSet<cajamovimc>();
            this.comisagens = new HashSet<comisagen>();
            this.liquidaciones = new HashSet<liquidacione>();
            this.dolares = new HashSet<dolare>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string corresponsal { get; set; }
        public string centro1 { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string contacto { get; set; }
        public string banco { get; set; }
        public string cuenta { get; set; }
        public string abal { get; set; }
        public string bcointerml { get; set; }
        public string bcoinctal { get; set; }
        public Nullable<int> ultimarec { get; set; }
        public Nullable<int> ultimaenv { get; set; }
        public string observaciones { get; set; }
        public string tope { get; set; }
        public string saldo { get; set; }
        public Nullable<System.DateTime> fechasal { get; set; }
        public Nullable<int> numlote { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string locka { get; set; }
        public string cuentapro { get; set; }
        public string contable { get; set; }
        public string numerico { get; set; }
        public string exacto { get; set; }
        public Nullable<int> tamano { get; set; }
        public string clave { get; set; }
        public string estado { get; set; }
    
        public virtual banco banco1 { get; set; }
        public virtual banco banco2 { get; set; }
        public virtual bcocuenta bcocuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bcomovim> bcomovims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cajamovimc> cajamovimcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comisagen> comisagens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidacione> liquidaciones { get; set; }
        public virtual ciudade ciudade { get; set; }
        public virtual corresponsale corresponsale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dolare> dolares { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
