//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cierre
    {
        public string caja { get; set; }
        public int cierre1 { get; set; }
        public Nullable<int> inicial { get; set; }
        public Nullable<int> final { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string personal { get; set; }
    }
}
