//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class clave
    {
        public string usuariocla { get; set; }
        public string tipo { get; set; }
        public System.DateTime desde { get; set; }
        public string clave1 { get; set; }
        public string referencia { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
