//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class comisagen
    {
        public string agencia { get; set; }
        public string centro { get; set; }
        public string r1hasta { get; set; }
        public string r1porcen { get; set; }
        public string r1min { get; set; }
        public string r2hasta { get; set; }
        public string r2porcen { get; set; }
        public string r2min { get; set; }
        public string e1hasta { get; set; }
        public string e1porcen { get; set; }
        public string e1min { get; set; }
        public string e2hasta { get; set; }
        public string e2porcen { get; set; }
        public string e2min { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual agencia agencia1 { get; set; }
        public virtual centro centro1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
