//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class comproban
    {
        public string tipo { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> fechacom { get; set; }
        public string tipoenti { get; set; }
        public string codigo { get; set; }
        public string ruc { get; set; }
        public string referencia { get; set; }
        public string modoimpres { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
        public string igv { get; set; }
        public string descripcion { get; set; }
        public string agencia { get; set; }
        public string origen { get; set; }
        public string voucher { get; set; }
        public string anulado { get; set; }
        public Nullable<System.DateTime> fechaanul { get; set; }
        public string motivoanul { get; set; }
        public string relaclase { get; set; }
        public string relaserie { get; set; }
        public string relanumero { get; set; }
        public string lotecon { get; set; }
        public string @interface { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string itf { get; set; }
        public string importen { get; set; }
        public string igvn { get; set; }
        public string itfotra { get; set; }
        public string serienc { get; set; }
        public string numeronc { get; set; }
        public Nullable<System.DateTime> fechanc { get; set; }
        public string usuarionc { get; set; }
        public Nullable<int> lotecom { get; set; }
        public string senalcom { get; set; }
        public Nullable<int> lotenc { get; set; }
        public string senalnc { get; set; }
        public Nullable<int> rollo { get; set; }
        public string senalro { get; set; }
        public Nullable<int> secuencia { get; set; }
        public string hora { get; set; }
        public string conta { get; set; }
        public string horanc { get; set; }
        public string contanc { get; set; }
    }
}
