//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class consueldo
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string abrevia { get; set; }
        public string siglas { get; set; }
        public string tipo { get; set; }
        public string rubro { get; set; }
        public string sunat { get; set; }
        public string importe { get; set; }
        public Nullable<int> afecto30 { get; set; }
        public Nullable<int> afecto31 { get; set; }
        public Nullable<int> afecto32 { get; set; }
        public Nullable<int> afecto33 { get; set; }
        public Nullable<int> afecto34 { get; set; }
        public Nullable<int> afecto35 { get; set; }
        public Nullable<int> afecto36 { get; set; }
        public Nullable<int> afecto37 { get; set; }
        public Nullable<int> afecto38 { get; set; }
        public Nullable<int> afecto39 { get; set; }
        public Nullable<int> afecto40 { get; set; }
        public Nullable<int> afecto41 { get; set; }
        public Nullable<int> afecto42 { get; set; }
        public Nullable<int> afecto43 { get; set; }
        public Nullable<int> afecto44 { get; set; }
        public Nullable<int> afecto45 { get; set; }
        public Nullable<int> afecto46 { get; set; }
        public Nullable<int> afecto47 { get; set; }
        public Nullable<int> afecto48 { get; set; }
        public Nullable<int> afecto49 { get; set; }
        public Nullable<int> afecto50 { get; set; }
        public Nullable<int> afecto51 { get; set; }
        public Nullable<int> afecto52 { get; set; }
        public Nullable<int> afecto53 { get; set; }
        public Nullable<int> afecto54 { get; set; }
        public Nullable<int> afecto55 { get; set; }
        public Nullable<int> afecto56 { get; set; }
        public Nullable<int> afecto57 { get; set; }
        public Nullable<int> afecto58 { get; set; }
        public Nullable<int> afecto59 { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> afecta { get; set; }
        public string provision { get; set; }
        public string ventas { get; set; }
        public string extra { get; set; }
    }
}
