//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public string numero { get; set; }
        public string cliente { get; set; }
        public string moneda { get; set; }
        public Nullable<System.DateTime> fechaini { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string saldoini { get; set; }
        public string saldo { get; set; }
        public string interes { get; set; }
        public string intereses { get; set; }
        public string retencion { get; set; }
        public string estado { get; set; }
        public string usuarioini { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public string referencia1 { get; set; }
        public string referencia2 { get; set; }
    }
}
