//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class contabled
    {
        public string operacion { get; set; }
        public string secuencia { get; set; }
        public string comprobante { get; set; }
        public string concepto { get; set; }
        public string tipopago { get; set; }
        public string moneda { get; set; }
        public string debehaber { get; set; }
        public string cuenta { get; set; }
        public string entidad { get; set; }
        public string adicional { get; set; }
        public string descripcion { get; set; }
        public string excluyente { get; set; }
        public string provision { get; set; }
        public string tipo { get; set; }
        public string ticambio { get; set; }
        public string codigo { get; set; }
    
        public virtual concepto concepto1 { get; set; }
    }
}
