//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class credito
    {
        public string serie { get; set; }
        public string numero { get; set; }
        public string tipocom { get; set; }
        public string seriecom { get; set; }
        public string numerocom { get; set; }
        public Nullable<System.DateTime> fechacom { get; set; }
        public string codigo { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
        public string igv { get; set; }
        public string itf { get; set; }
        public string agencia { get; set; }
        public string origen { get; set; }
        public string voucher { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
