//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct
    {
        public string codigo { get; set; }
        public string ano { get; set; }
        public string semestre { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string totaldias { get; set; }
        public string faltas { get; set; }
        public string diasneto { get; set; }
        public string ganan10 { get; set; }
        public string ganan11 { get; set; }
        public string ganan12 { get; set; }
        public string ganan13 { get; set; }
        public string ganan14 { get; set; }
        public string ganan15 { get; set; }
        public string ganan16 { get; set; }
        public string ganan17 { get; set; }
        public string ganan18 { get; set; }
        public string ganan19 { get; set; }
        public string grati { get; set; }
        public string gratimes { get; set; }
        public string sobre { get; set; }
        public string sobremes { get; set; }
        public string total { get; set; }
        public string ctssoles { get; set; }
        public string ctsdolar { get; set; }
        public string ticambio { get; set; }
        public string banco { get; set; }
        public string cuenta { get; set; }
        public string moneda { get; set; }
        public string fechabco { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
