//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class denuncia
    {
        public string numero { get; set; }
        public string referencia { get; set; }
        public string texto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string solutexto { get; set; }
        public string soluusuario { get; set; }
        public Nullable<System.DateTime> solufecha { get; set; }
        public string soluhora { get; set; }
        public string estado { get; set; }
    }
}
