//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinosd
    {
        public string destino { get; set; }
        public string tipo { get; set; }
        public int hasta { get; set; }
        public string tariporcen { get; set; }
        public string tarimin { get; set; }
        public string tarifijo { get; set; }
        public string comiporcen { get; set; }
        public string comimin { get; set; }
        public string comifijo { get; set; }
    
        public virtual destino destino1 { get; set; }
    }
}
