//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class domingo
    {
        public string agencia { get; set; }
        public System.DateTime fecha { get; set; }
        public string turno1personal { get; set; }
        public Nullable<int> turno1obliga { get; set; }
        public Nullable<System.DateTime> turno1descansa { get; set; }
        public string turno2personal { get; set; }
        public Nullable<int> turno2obliga { get; set; }
        public Nullable<System.DateTime> turno2descansa { get; set; }
        public string turno3personal { get; set; }
        public Nullable<int> turno3obliga { get; set; }
        public Nullable<System.DateTime> turno3descansa { get; set; }
        public string turno0personal { get; set; }
        public Nullable<int> turno0obliga { get; set; }
        public Nullable<System.DateTime> turno0descansa { get; set; }
    }
}
