//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class errore
    {
        public string clase { get; set; }
        public string giro { get; set; }
        public string referencia { get; set; }
        public string agencia { get; set; }
        public string caja { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string monedam { get; set; }
        public string importem { get; set; }
    }
}
