//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public string codigo { get; set; }
        public string tipo { get; set; }
        public string numero { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
        public string rubro { get; set; }
        public Nullable<System.DateTime> fechafact { get; set; }
        public Nullable<System.DateTime> fechareci { get; set; }
        public Nullable<System.DateTime> fechaprog { get; set; }
        public Nullable<System.DateTime> fecharegi { get; set; }
        public string recibefa { get; set; }
        public string registra { get; set; }
        public string fechapago { get; set; }
        public string paga { get; set; }
        public string cajabanco { get; set; }
        public string codigocb { get; set; }
        public string voucher { get; set; }
        public string fechaentrega { get; set; }
        public string entrega { get; set; }
        public string recibepa { get; set; }
        public string estado { get; set; }
        public string referen { get; set; }
    }
}
