//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcoperac
    {
        public string ruc { get; set; }
        public string codigo { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string clase { get; set; }
        public string valor { get; set; }
        public string obliga { get; set; }
        public string documento { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
