//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fedex
    {
        public string corporativo { get; set; }
        public string hasta { get; set; }
        public string comision { get; set; }
        public string hasta1 { get; set; }
        public string adicional1 { get; set; }
        public string hasta2 { get; set; }
        public string adicional2 { get; set; }
        public string hasta3 { get; set; }
        public string adicional3 { get; set; }
        public string hasta4 { get; set; }
        public string adicional4 { get; set; }
        public string comiagen { get; set; }
        public Nullable<int> numero { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
