//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gananper
    {
        public string codigo { get; set; }
        public System.DateTime desde { get; set; }
        public string importe1 { get; set; }
        public string importe2 { get; set; }
        public string importe3 { get; set; }
        public string importe4 { get; set; }
        public string importe5 { get; set; }
        public string importe6 { get; set; }
        public string importe7 { get; set; }
        public string importe8 { get; set; }
        public string importe9 { get; set; }
        public string referen { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
