//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GirosEntities : DbContext
    {
        public GirosEntities()
            : base("name=GirosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accontrol> accontrols { get; set; }
        public virtual DbSet<activoc> activocs { get; set; }
        public virtual DbSet<activod> activods { get; set; }
        public virtual DbSet<acumulado> acumulados { get; set; }
        public virtual DbSet<adelanto> adelantoes { get; set; }
        public virtual DbSet<adenda> adendas { get; set; }
        public virtual DbSet<adipersonal> adipersonals { get; set; }
        public virtual DbSet<agenage> agenages { get; set; }
        public virtual DbSet<agenban> agenbans { get; set; }
        public virtual DbSet<agencia> agencias { get; set; }
        public virtual DbSet<agenmovim> agenmovims { get; set; }
        public virtual DbSet<agenoper> agenopers { get; set; }
        public virtual DbSet<agenopera> agenoperas { get; set; }
        public virtual DbSet<agentesglobo> agentesgloboes { get; set; }
        public virtual DbSet<asignacion> asignacions { get; set; }
        public virtual DbSet<banco> bancos { get; set; }
        public virtual DbSet<bcocomi> bcocomis { get; set; }
        public virtual DbSet<bcocuenta> bcocuentas { get; set; }
        public virtual DbSet<bcomovim> bcomovims { get; set; }
        public virtual DbSet<bcooperac> bcooperacs { get; set; }
        public virtual DbSet<bcorefer> bcorefers { get; set; }
        public virtual DbSet<cajacierre> cajacierres { get; set; }
        public virtual DbSet<cajamovimc> cajamovimcs { get; set; }
        public virtual DbSet<cajamovimd> cajamovimds { get; set; }
        public virtual DbSet<cajaoper> cajaopers { get; set; }
        public virtual DbSet<caja> cajas { get; set; }
        public virtual DbSet<cajasaldo> cajasaldoes { get; set; }
        public virtual DbSet<cajavario> cajavarios { get; set; }
        public virtual DbSet<calendario> calendarios { get; set; }
        public virtual DbSet<cambiocorr> cambiocorrs { get; set; }
        public virtual DbSet<cargamg> cargamgs { get; set; }
        public virtual DbSet<cargo> cargos { get; set; }
        public virtual DbSet<cartera> carteras { get; set; }
        public virtual DbSet<catalogo> catalogoes { get; set; }
        public virtual DbSet<centro> centros { get; set; }
        public virtual DbSet<cheque> cheques { get; set; }
        public virtual DbSet<cierre> cierres { get; set; }
        public virtual DbSet<ciiu> ciius { get; set; }
        public virtual DbSet<ciudade> ciudades { get; set; }
        public virtual DbSet<clas> clases { get; set; }
        public virtual DbSet<clave> claves { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<clientex> clientexes { get; set; }
        public virtual DbSet<comisagen> comisagens { get; set; }
        public virtual DbSet<comproban> comprobans { get; set; }
        public virtual DbSet<concepto> conceptos { get; set; }
        public virtual DbSet<concluido> concluidos { get; set; }
        public virtual DbSet<conpago> conpagos { get; set; }
        public virtual DbSet<consueldo> consueldos { get; set; }
        public virtual DbSet<contablec> contablecs { get; set; }
        public virtual DbSet<contabled> contableds { get; set; }
        public virtual DbSet<contrato> contratos { get; set; }
        public virtual DbSet<corresponsale> corresponsales { get; set; }
        public virtual DbSet<credito> creditoes { get; set; }
        public virtual DbSet<ct> cts { get; set; }
        public virtual DbSet<cuarta> cuartas { get; set; }
        public virtual DbSet<cuenta> cuentas { get; set; }
        public virtual DbSet<denuncia> denuncias { get; set; }
        public virtual DbSet<departa> departas { get; set; }
        public virtual DbSet<destino> destinos { get; set; }
        public virtual DbSet<destinosd> destinosds { get; set; }
        public virtual DbSet<distrito> distritos { get; set; }
        public virtual DbSet<documento> documentos { get; set; }
        public virtual DbSet<dolare> dolares { get; set; }
        public virtual DbSet<domingo> domingos { get; set; }
        public virtual DbSet<empleadore> empleadores { get; set; }
        public virtual DbSet<envio> envios { get; set; }
        public virtual DbSet<errore> errores { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<familiar> familiars { get; set; }
        public virtual DbSet<fcoperac> fcoperacs { get; set; }
        public virtual DbSet<fedex> fedexes { get; set; }
        public virtual DbSet<formacion> formacions { get; set; }
        public virtual DbSet<gananper> gananpers { get; set; }
        public virtual DbSet<girosnac> girosnacs { get; set; }
        public virtual DbSet<gratifica> gratificas { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<guinazu> guinazus { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<ingreper> ingrepers { get; set; }
        public virtual DbSet<institucione> instituciones { get; set; }
        public virtual DbSet<interage> interages { get; set; }
        public virtual DbSet<intermex> intermexes { get; set; }
        public virtual DbSet<intermovim> intermovims { get; set; }
        public virtual DbSet<interoperac> interoperacs { get; set; }
        public virtual DbSet<intertran> intertrans { get; set; }
        public virtual DbSet<inusual> inusuals { get; set; }
        public virtual DbSet<juridico> juridicos { get; set; }
        public virtual DbSet<kardex> kardexes { get; set; }
        public virtual DbSet<laboral> laborals { get; set; }
        public virtual DbSet<liquida> liquidas { get; set; }
        public virtual DbSet<liquidacione> liquidaciones { get; set; }
        public virtual DbSet<localidade> localidades { get; set; }
        public virtual DbSet<logclien> logcliens { get; set; }
        public virtual DbSet<logpago> logpagos { get; set; }
        public virtual DbSet<lotescon> lotescons { get; set; }
        public virtual DbSet<marcacion> marcacions { get; set; }
        public virtual DbSet<mbocupa> mbocupas { get; set; }
        public virtual DbSet<mbsubagen> mbsubagens { get; set; }
        public virtual DbSet<mbubigeo> mbubigeos { get; set; }
        public virtual DbSet<mgcomi> mgcomis { get; set; }
        public virtual DbSet<mgram> mgrams { get; set; }
        public virtual DbSet<moneda> monedas { get; set; }
        public virtual DbSet<moneye> moneyes { get; set; }
        public virtual DbSet<nacional> nacionals { get; set; }
        public virtual DbSet<objeto> objetos { get; set; }
        public virtual DbSet<obligado> obligados { get; set; }
        public virtual DbSet<ocupa> ocupas { get; set; }
        public virtual DbSet<ofac> ofacs { get; set; }
        public virtual DbSet<opcione> opciones { get; set; }
        public virtual DbSet<operaact> operaacts { get; set; }
        public virtual DbSet<orbi> orbis { get; set; }
        public virtual DbSet<pago> pagos { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<paisesmg> paisesmgs { get; set; }
        public virtual DbSet<patrim> patrims { get; set; }
        public virtual DbSet<perfile> perfiles { get; set; }
        public virtual DbSet<periodo> periodos { get; set; }
        public virtual DbSet<permiso> permisoes { get; set; }
        public virtual DbSet<persocaja> persocajas { get; set; }
        public virtual DbSet<persodia> persodias { get; set; }
        public virtual DbSet<personal> personals { get; set; }
        public virtual DbSet<postal> postals { get; set; }
        public virtual DbSet<prestamo> prestamoes { get; set; }
        public virtual DbSet<presupuesto> presupuestoes { get; set; }
        public virtual DbSet<provision> provisions { get; set; }
        public virtual DbSet<queja> quejas { get; set; }
        public virtual DbSet<reclamonu> reclamonus { get; set; }
        public virtual DbSet<reclamo> reclamos { get; set; }
        public virtual DbSet<reclamoti> reclamotis { get; set; }
        public virtual DbSet<reclaopenu> reclaopenus { get; set; }
        public virtual DbSet<reclaopera> reclaoperas { get; set; }
        public virtual DbSet<remunera> remuneras { get; set; }
        public virtual DbSet<remunerad> remunerads { get; set; }
        public virtual DbSet<resuman> resumen { get; set; }
        public virtual DbSet<riafex> riafexes { get; set; }
        public virtual DbSet<riesgo> riesgos { get; set; }
        public virtual DbSet<rorope> roropes { get; set; }
        public virtual DbSet<ro> ros { get; set; }
        public virtual DbSet<rubro> rubros { get; set; }
        public virtual DbSet<seccione> secciones { get; set; }
        public virtual DbSet<servicio> servicios { get; set; }
        public virtual DbSet<sole> soles { get; set; }
        public virtual DbSet<sospechan> sospechans { get; set; }
        public virtual DbSet<sospecha> sospechas { get; set; }
        public virtual DbSet<sunat> sunats { get; set; }
        public virtual DbSet<tablasr> tablasrs { get; set; }
        public virtual DbSet<tablast> tablasts { get; set; }
        public virtual DbSet<tarifa> tarifas { get; set; }
        public virtual DbSet<tarifasnac> tarifasnacs { get; set; }
        public virtual DbSet<tercero> terceros { get; set; }
        public virtual DbSet<ticambio> ticambios { get; set; }
        public virtual DbSet<ticambioage> ticambioages { get; set; }
        public virtual DbSet<ticambio1> ticambioes { get; set; }
        public virtual DbSet<ticheque> ticheques { get; set; }
        public virtual DbSet<ticlave> ticlaves { get; set; }
        public virtual DbSet<tipago> tipagoes { get; set; }
        public virtual DbSet<tipocom> tipocoms { get; set; }
        public virtual DbSet<titan> titans { get; set; }
        public virtual DbSet<titanlog> titanlogs { get; set; }
        public virtual DbSet<totalagen> totalagens { get; set; }
        public virtual DbSet<totalme> totalmes { get; set; }
        public virtual DbSet<transaccione> transacciones { get; set; }
        public virtual DbSet<travel> travels { get; set; }
        public virtual DbSet<travelsal> travelsals { get; set; }
        public virtual DbSet<trf> trfs { get; set; }
        public virtual DbSet<ubigeo> ubigeos { get; set; }
        public virtual DbSet<unica> unicas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuavar> usuavars { get; set; }
        public virtual DbSet<utilidad> utilidads { get; set; }
        public virtual DbSet<utilidade> utilidades { get; set; }
        public virtual DbSet<vacacione> vacaciones { get; set; }
        public virtual DbSet<valormn> valormns { get; set; }
        public virtual DbSet<viamerica> viamericas { get; set; }
        public virtual DbSet<log_triggers> log_triggers { get; set; }
    }
}
