//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class girosnac
    {
        public string numero { get; set; }
        public string moneda { get; set; }
        public string importe { get; set; }
        public string tarifa { get; set; }
        public Nullable<int> estado { get; set; }
        public string mensaje { get; set; }
        public string observaciones { get; set; }
        public string agenciaori { get; set; }
        public string cajaori { get; set; }
        public string clienteori { get; set; }
        public Nullable<int> tipopago { get; set; }
        public string cuenta { get; set; }
        public string documento { get; set; }
        public Nullable<System.DateTime> fechadoc { get; set; }
        public string movimori { get; set; }
        public Nullable<System.DateTime> fechaori { get; set; }
        public string horaori { get; set; }
        public string usuarioori { get; set; }
        public string comisaori { get; set; }
        public string agenciades { get; set; }
        public string cajades { get; set; }
        public string clientedes { get; set; }
        public string movimdes { get; set; }
        public Nullable<System.DateTime> fechades { get; set; }
        public string horades { get; set; }
        public string usuariodes { get; set; }
        public string comisades { get; set; }
        public string itf { get; set; }
        public Nullable<int> sunat { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public string lotecon { get; set; }
        public string lotecon1 { get; set; }
        public Nullable<System.DateTime> fecharch1 { get; set; }
        public string usuarch1 { get; set; }
        public Nullable<System.DateTime> fecharch2 { get; set; }
        public string usuarch2 { get; set; }
        public string tarifan { get; set; }
        public string itfn { get; set; }
        public string igv { get; set; }
        public string referen { get; set; }
        public string loteanu { get; set; }
        public string bloqueado { get; set; }
        public string referencia { get; set; }
        public string globonumero { get; set; }
        public string globoori { get; set; }
        public string globodes { get; set; }
        public string globokas { get; set; }
        public string portes { get; set; }
        public string globokasbeneficiario { get; set; }
    }
}
