//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class gratifica
    {
        public string codigo { get; set; }
        public string semestre { get; set; }
        public string sueldo { get; set; }
        public string familiar { get; set; }
        public string riesgo { get; set; }
        public string mes1sobre { get; set; }
        public string mes2sobre { get; set; }
        public string mes3sobre { get; set; }
        public string mes4sobre { get; set; }
        public string mes5sobre { get; set; }
        public string mes6sobre { get; set; }
        public string mes1otros { get; set; }
        public string mes2otros { get; set; }
        public string mes3otros { get; set; }
        public string mes4otros { get; set; }
        public string mes5otros { get; set; }
        public string mes6otros { get; set; }
        public Nullable<System.DateTime> ingreso { get; set; }
        public string diassem { get; set; }
        public string factor { get; set; }
        public string mesessobre { get; set; }
        public string mesesotros { get; set; }
        public string totalfijas { get; set; }
        public string totalsobre { get; set; }
        public string totalotros { get; set; }
        public string porcenbo { get; set; }
        public string bonifica { get; set; }
        public string estado { get; set; }
        public Nullable<int> adelanto { get; set; }
        public string cartera { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
