//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string razon { get; set; }
        public string ruc { get; set; }
        public string globotcc { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> ultimadolar { get; set; }
        public Nullable<System.DateTime> ultimasoles { get; set; }
        public Nullable<System.DateTime> ultimaeuros { get; set; }
    }
}
