//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public string agencia { get; set; }
        public string dia { get; set; }
        public string atendesde { get; set; }
        public string atenhasta { get; set; }
        public string turno1desde { get; set; }
        public string turno1hasta { get; set; }
        public Nullable<int> turno1refri { get; set; }
        public string turno2desde { get; set; }
        public string turno2hasta { get; set; }
        public Nullable<int> turno2refri { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string turno3desde { get; set; }
        public string turno3hasta { get; set; }
        public Nullable<int> turno3refri { get; set; }
    }
}
