//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreper
    {
        public string codigo { get; set; }
        public System.DateTime desde { get; set; }
        public string importe10 { get; set; }
        public string importe11 { get; set; }
        public string importe12 { get; set; }
        public string importe13 { get; set; }
        public string importe14 { get; set; }
        public string importe15 { get; set; }
        public string importe16 { get; set; }
        public string importe17 { get; set; }
        public string importe18 { get; set; }
        public string importe19 { get; set; }
        public string referen { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
