//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class institucione
    {
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string clase { get; set; }
        public string afpaporte { get; set; }
        public string afpseguro { get; set; }
        public string afpcomision { get; set; }
        public string afptope { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string provision { get; set; }
        public string afpmixta { get; set; }
    }
}
