//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class intertran
    {
        public int numero { get; set; }
        public string referen { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string agencia { get; set; }
        public string importe { get; set; }
        public string modopago { get; set; }
        public string banco { get; set; }
        public string cuenta { get; set; }
        public string remitente { get; set; }
        public string mensaje { get; set; }
        public string pais { get; set; }
        public string persona { get; set; }
        public string documento { get; set; }
        public string cliente { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
    }
}
