//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class intermovim
    {
        public string caja { get; set; }
        public string numero { get; set; }
        public string agencia { get; set; }
        public string operacion { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string ingsal { get; set; }
        public string importe { get; set; }
        public string comision { get; set; }
        public string referencia { get; set; }
        public string observaciones { get; set; }
        public string cartera { get; set; }
        public string anulada { get; set; }
        public string relacionado { get; set; }
        public Nullable<System.DateTime> fechaliquida { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numliquida { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
