//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboral
    {
        public string codigo { get; set; }
        public string tipo { get; set; }
        public string regimen { get; set; }
        public string niveledu { get; set; }
        public string ocupacion { get; set; }
        public string ticontrato { get; set; }
        public string periodicidad { get; set; }
        public string situacion { get; set; }
        public string tipopago { get; set; }
        public string categoria { get; set; }
        public string discapacidad { get; set; }
        public string alternativo { get; set; }
        public string maxima { get; set; }
        public string nocturno { get; set; }
        public string exonerado { get; set; }
        public string especial { get; set; }
        public string clase { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string otra { get; set; }
    }
}
