//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class logclien
    {
        public string codigo { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string personeria { get; set; }
        public string tipodoc { get; set; }
        public string usuario { get; set; }
        public string descri { get; set; }
    }
}
