//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class logpago
    {
        public string numero { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string importe { get; set; }
        public Nullable<int> tipopago { get; set; }
        public string age_ciu_bco { get; set; }
        public string tipocta { get; set; }
        public string cuenta { get; set; }
        public string usuario { get; set; }
        public string descri { get; set; }
        public string nombre { get; set; }
        public string orden { get; set; }
    }
}
