//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofac
    {
        public string numero { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string fecha { get; set; }
        public string ciudad { get; set; }
        public string pasapor { get; set; }
        public string cedula { get; set; }
        public string identi { get; set; }
        public string observaciones { get; set; }
    }
}
