//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcione
    {
        public string perfil { get; set; }
        public string transacc { get; set; }
        public string actualiza { get; set; }
        public string opcion { get; set; }
    
        public virtual perfile perfile { get; set; }
        public virtual transaccione transaccione { get; set; }
    }
}
