//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class orbi
    {
        public string comision { get; set; }
        public string comisage { get; set; }
        public string codigosol { get; set; }
        public string codigodol { get; set; }
        public string unicassol { get; set; }
        public string unicasdol { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
