//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public string numero { get; set; }
        public string localidad { get; set; }
        public string orden { get; set; }
        public string cliente { get; set; }
        public string remitente { get; set; }
        public string importe { get; set; }
        public string comision { get; set; }
        public string consigna { get; set; }
        public Nullable<int> tipopago { get; set; }
        public string age_ciu_bco { get; set; }
        public string tipocta { get; set; }
        public string cuenta { get; set; }
        public string mensaje { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public Nullable<System.DateTime> fechainc { get; set; }
        public string horainc { get; set; }
        public Nullable<System.DateTime> fechaver { get; set; }
        public Nullable<System.DateTime> fechalla { get; set; }
        public Nullable<System.DateTime> fechabo { get; set; }
        public Nullable<System.DateTime> fechacan { get; set; }
        public string horacan { get; set; }
        public string operacan { get; set; }
        public string clavecan { get; set; }
        public string destino { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comisa { get; set; }
        public string provincia { get; set; }
        public string caja { get; set; }
        public string origen { get; set; }
        public string bcocuenta { get; set; }
        public string documento { get; set; }
        public string movim { get; set; }
        public Nullable<System.DateTime> fechabco { get; set; }
        public string horalla { get; set; }
        public string usualla { get; set; }
        public string cajaag { get; set; }
        public string movimag { get; set; }
        public Nullable<System.DateTime> fechapro { get; set; }
        public string itf { get; set; }
        public Nullable<int> sunat { get; set; }
        public string pais { get; set; }
        public string mone_refer { get; set; }
        public string mone_lote { get; set; }
        public Nullable<System.DateTime> mone_fecha { get; set; }
        public string usuainco { get; set; }
        public string usuapaga { get; set; }
        public string usuaveri { get; set; }
        public string usuavoucher { get; set; }
        public string cerrado { get; set; }
        public string lotecon { get; set; }
        public string lotecon1 { get; set; }
        public string viam_lote { get; set; }
        public Nullable<System.DateTime> viam_fecha { get; set; }
        public string abonobco { get; set; }
        public string bloqueado { get; set; }
        public string usuapro { get; set; }
        public string subagen { get; set; }
        public Nullable<System.DateTime> fecharch { get; set; }
        public string usuarch { get; set; }
        public string ciudad { get; set; }
        public string moneda { get; set; }
        public string soles { get; set; }
        public string itfsol { get; set; }
        public string clientex { get; set; }
        public string usuaincon { get; set; }
        public string usuapagan { get; set; }
        public string diferencia { get; set; }
        public string cambiohis { get; set; }
        public string liquidado { get; set; }
        public string vigorefe { get; set; }
    }
}
