//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public string codigo { get; set; }
        public int secuencia { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fechade { get; set; }
        public Nullable<System.DateTime> fechaa { get; set; }
        public string horade { get; set; }
        public string horaa { get; set; }
        public string citt { get; set; }
        public string motivo { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string clase { get; set; }
    }
}
