//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public string codigo { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string seccion { get; set; }
        public string observaciones { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string asisten { get; set; }
        public string refrige { get; set; }
        public string sobretpo { get; set; }
        public string planilla { get; set; }
        public string documento { get; set; }
        public string clase { get; set; }
        public string estadoci { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string celular { get; set; }
        public string mail { get; set; }
        public string postal { get; set; }
        public string ciudad { get; set; }
        public string nacion { get; set; }
        public Nullable<System.DateTime> nacim { get; set; }
        public string profesion { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> fechaingr { get; set; }
        public Nullable<System.DateTime> fechacese { get; set; }
        public string horasdia { get; set; }
        public string horasmes { get; set; }
        public string pension { get; set; }
        public string afp { get; set; }
        public string cuspp { get; set; }
        public string agencia { get; set; }
        public string bcocts { get; set; }
        public string jubilado { get; set; }
        public string cuentacts { get; set; }
        public string monedacts { get; set; }
        public string comision { get; set; }
        public string domingos { get; set; }
        public string sabados { get; set; }
        public string turno { get; set; }
        public Nullable<System.DateTime> fechaesta { get; set; }
        public string cuentasueldo { get; set; }
    
        public virtual cajavario cajavario { get; set; }
        public virtual seccione seccione { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
