//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        public string periodo { get; set; }
        public string agencia { get; set; }
        public string tipo { get; set; }
        public string concepto { get; set; }
        public string mes01 { get; set; }
        public string mes02 { get; set; }
        public string mes03 { get; set; }
        public string mes04 { get; set; }
        public string mes05 { get; set; }
        public string mes06 { get; set; }
        public string mes07 { get; set; }
        public string mes08 { get; set; }
        public string mes09 { get; set; }
        public string mes10 { get; set; }
        public string mes11 { get; set; }
        public string mes12 { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
