//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public string codigo { get; set; }
        public int secuencia { get; set; }
        public string importe { get; set; }
        public string meses { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
        public string inicial { get; set; }
        public string restantes { get; set; }
        public string estado { get; set; }
        public string movimcar { get; set; }
        public string usuarioreg { get; set; }
        public Nullable<System.DateTime> fechareg { get; set; }
        public string usuarioapro { get; set; }
        public Nullable<System.DateTime> fechaapro { get; set; }
        public Nullable<System.DateTime> fechadescto { get; set; }
        public string descontado { get; set; }
        public string referen { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
