//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class provision
    {
        public string cajabanco { get; set; }
        public string codigo { get; set; }
        public string numero { get; set; }
        public int secuencia { get; set; }
        public string moneda { get; set; }
        public Nullable<System.DateTime> fechadoc { get; set; }
        public string igv { get; set; }
        public string total { get; set; }
        public string referencia { get; set; }
        public string spotnumero { get; set; }
        public Nullable<System.DateTime> spotfecha { get; set; }
        public string spotimpor { get; set; }
        public Nullable<System.DateTime> fechaven { get; set; }
        public string estado { get; set; }
        public string concepto { get; set; }
        public string importe { get; set; }
        public string tipo { get; set; }
        public string clase { get; set; }
        public string percepcion { get; set; }
        public string entidad { get; set; }
        public string tipoco { get; set; }
        public string comprobante { get; set; }
        public string detbanco { get; set; }
        public string detnumero { get; set; }
        public string detcancel { get; set; }
        public string spotnumeron { get; set; }
    }
}
