//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclamo
    {
        public string numero { get; set; }
        public string cliente { get; set; }
        public string regusuario { get; set; }
        public string regagencia { get; set; }
        public string regemple { get; set; }
        public Nullable<System.DateTime> regfecha { get; set; }
        public string reghora { get; set; }
        public string causaagencia { get; set; }
        public string causaemple { get; set; }
        public Nullable<System.DateTime> causafecha { get; set; }
        public string causahora { get; set; }
        public string operacion { get; set; }
        public string motivo { get; set; }
        public string texto { get; set; }
        public string soluemple { get; set; }
        public Nullable<System.DateTime> solufecha { get; set; }
        public string soluhora { get; set; }
        public string solutexto { get; set; }
        public string entreusuario { get; set; }
        public string entreagencia { get; set; }
        public string entreemple { get; set; }
        public Nullable<System.DateTime> entrefecha { get; set; }
        public string entrehora { get; set; }
        public string estado { get; set; }
        public string favor { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observa { get; set; }
        public Nullable<int> transac { get; set; }
        public string voucher { get; set; }
        public string boleta { get; set; }
        public string revision { get; set; }
        public string operanu { get; set; }
        public string motivonu { get; set; }
        public string medio { get; set; }
        public string relacionado { get; set; }
        public string observaentre { get; set; }
        public string aprousuario { get; set; }
        public string aproemple { get; set; }
        public Nullable<System.DateTime> aprofecha { get; set; }
        public string aprohora { get; set; }
        public string fichausuario { get; set; }
        public string fichaemple { get; set; }
        public Nullable<System.DateTime> fichafecha { get; set; }
        public string fichahora { get; set; }
        public string cerrusuario { get; set; }
        public string cerremple { get; set; }
        public Nullable<System.DateTime> cerrfecha { get; set; }
        public string cerrhora { get; set; }
    }
}
