//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class remunerad
    {
        public string codigo { get; set; }
        public string ano { get; set; }
        public string mes { get; set; }
        public string clase { get; set; }
        public string concepto { get; set; }
        public string importe { get; set; }
        public string teorico { get; set; }
        public string liquida { get; set; }
    }
}
