//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class remunera
    {
        public string codigo { get; set; }
        public string ano { get; set; }
        public string mes { get; set; }
        public string clase { get; set; }
        public string dia { get; set; }
        public string hteomes { get; set; }
        public string hteodia { get; set; }
        public string htrabaja { get; set; }
        public string hsobre25 { get; set; }
        public string hsobre35 { get; set; }
        public string hsobre100 { get; set; }
        public string hvacatra { get; set; }
        public string hfaltas { get; set; }
        public string hneto { get; set; }
        public string diastraba { get; set; }
        public string diasvaca { get; set; }
        public string pension { get; set; }
        public string codiafp { get; set; }
        public string remantes5 { get; set; }
        public string rembru5 { get; set; }
        public string remanual5 { get; set; }
        public string anual5 { get; set; }
        public string retenido5 { get; set; }
        public string restante5 { get; set; }
        public string observaciones { get; set; }
        public string pagototal { get; set; }
        public string movim { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string subsidia { get; set; }
        public string aporte { get; set; }
        public string seguro { get; set; }
        public string comision { get; set; }
        public string tope { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string htardas { get; set; }
        public string liquida { get; set; }
    }
}
