//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class resuman
    {
        public string ano { get; set; }
        public string mes { get; set; }
        public string recibidos { get; set; }
        public string enviados { get; set; }
        public string nacenvsol { get; set; }
        public string nacenvdol { get; set; }
        public string nacrecsol { get; set; }
        public string nacrecdol { get; set; }
        public string clientessol { get; set; }
        public string clientesdol { get; set; }
    }
}
