//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgo
    {
        public string cliente { get; set; }
        public string personeria { get; set; }
        public string califica01 { get; set; }
        public string califica02 { get; set; }
        public string califica03 { get; set; }
        public string califica04 { get; set; }
        public string califica05 { get; set; }
        public string califica06 { get; set; }
        public string califica07 { get; set; }
        public string califica08 { get; set; }
        public string califica09 { get; set; }
        public string califica10 { get; set; }
        public string califica11 { get; set; }
        public string califica12 { get; set; }
        public string promedio { get; set; }
        public string etapa { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string mensaje { get; set; }
    }
}
