//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro
    {
        public string cliente { get; set; }
        public int numero { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
        public string operacion { get; set; }
        public string opera1 { get; set; }
        public string opera2 { get; set; }
        public string opera3 { get; set; }
        public string opera4 { get; set; }
        public string opera5 { get; set; }
        public string opera6 { get; set; }
        public string opera7 { get; set; }
        public string opera8 { get; set; }
        public string opera9 { get; set; }
        public string voucher { get; set; }
        public string nacional { get; set; }
        public string internac { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string agencia { get; set; }
        public string importe { get; set; }
        public Nullable<System.DateTime> fechainf { get; set; }
        public string reporte { get; set; }
        public string referean { get; set; }
        public string condicion { get; set; }
        public string relacion { get; set; }
        public string cual { get; set; }
        public string vinculada { get; set; }
        public string novincu { get; set; }
        public Nullable<System.DateTime> fecharet { get; set; }
        public string documento1 { get; set; }
        public string documento2 { get; set; }
        public string documento3 { get; set; }
        public string documento4 { get; set; }
        public string documento5 { get; set; }
        public string documento6 { get; set; }
        public string comentarios { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
