//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rorope
    {
        public string tipo { get; set; }
        public string periodo { get; set; }
        public string fila { get; set; }
        public string oficina { get; set; }
        public string registro { get; set; }
        public string recienvi { get; set; }
        public string giro { get; set; }
        public string referencia { get; set; }
        public string modalidad { get; set; }
        public string ubigeo { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string hora { get; set; }
        public string cliente { get; set; }
        public string clientex { get; set; }
        public string efectivo { get; set; }
        public string importe { get; set; }
        public string ticambio { get; set; }
        public string paisorigen { get; set; }
        public string paisdestino { get; set; }
        public string ventanilla { get; set; }
        public string otros { get; set; }
        public string verificado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string unicas { get; set; }
        public string apartir { get; set; }
        public string acumulado { get; set; }
        public string corresp { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
