//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubro
    {
        public string codigo { get; set; }
        public string ctacon { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ctacon2 { get; set; }
        public string spot { get; set; }
        public string vencim { get; set; }
        public string minimo { get; set; }
        public string abrevia { get; set; }
        public string estado { get; set; }
        public string nombre { get; set; }
        public string concepto { get; set; }
        public string conta3 { get; set; }
        public string conta4 { get; set; }
        public string tipo { get; set; }
    }
}
