//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public string empresa { get; set; }
        public string caja { get; set; }
        public string numero { get; set; }
        public string tipo { get; set; }
        public string operacion { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string hora { get; set; }
        public string importe { get; set; }
        public string comision { get; set; }
        public string documento { get; set; }
        public string observaciones { get; set; }
        public string facbol { get; set; }
        public string serie { get; set; }
        public string compro { get; set; }
        public string grupo { get; set; }
        public string estado { get; set; }
        public string liqfactura { get; set; }
        public Nullable<System.DateTime> liqfecha { get; set; }
        public string lotecon { get; set; }
        public string numcartera { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numcar { get; set; }
        public string liqfactura2 { get; set; }
        public Nullable<System.DateTime> liqfecha2 { get; set; }
        public string numcar2 { get; set; }
        public string lotecon1 { get; set; }
        public string gasolina { get; set; }
        public string moneda { get; set; }
        public string corporativo { get; set; }
        public string pais { get; set; }
        public string postal { get; set; }
        public Nullable<int> secuencia { get; set; }
        public string agencia { get; set; }
    }
}
