//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sole
    {
        public string numero { get; set; }
        public string origen { get; set; }
        public string codigo { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> feche { get; set; }
        public string numche { get; set; }
        public string banco { get; set; }
        public string importe { get; set; }
        public string comision { get; set; }
        public string comiche { get; set; }
        public string observaciones { get; set; }
        public string usuarioin { get; set; }
        public Nullable<System.DateTime> fechain { get; set; }
        public string horain { get; set; }
        public string anulado { get; set; }
        public Nullable<System.DateTime> trafecha { get; set; }
        public string tracuenta { get; set; }
        public string tralote { get; set; }
        public Nullable<System.DateTime> liqfecha { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string caja { get; set; }
        public string oripa { get; set; }
        public string lotecaja { get; set; }
        public string movim { get; set; }
        public string tracaja { get; set; }
        public string traoripa { get; set; }
        public string tracajalote { get; set; }
        public string tramovim { get; set; }
        public string consigna { get; set; }
        public string dolares { get; set; }
        public string compporte { get; set; }
        public string boveda { get; set; }
        public string lotecon { get; set; }
    }
}
