//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sospechan
    {
        public int operacion { get; set; }
        public string guia { get; set; }
        public int clase { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string usuario { get; set; }
        public Nullable<int> tipo { get; set; }
        public string importe { get; set; }
        public string referencia { get; set; }
        public Nullable<int> lote { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string referencia2 { get; set; }
        public string sospe { get; set; }
        public string comentarioc { get; set; }
        public Nullable<System.DateTime> fechac { get; set; }
        public string horac { get; set; }
        public string usuarioc { get; set; }
        public string condicion { get; set; }
        public Nullable<int> pep { get; set; }
        public Nullable<int> ros { get; set; }
        public Nullable<int> judi { get; set; }
        public Nullable<int> obli { get; set; }
        public Nullable<int> tele { get; set; }
        public Nullable<int> semes { get; set; }
        public Nullable<int> noper { get; set; }
        public Nullable<int> mismo { get; set; }
        public Nullable<int> multi { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> remi { get; set; }
        public Nullable<int> pais { get; set; }
        public Nullable<int> ubi { get; set; }
        public Nullable<int> redes { get; set; }
        public Nullable<int> numero { get; set; }
        public string usuarioau { get; set; }
    }
}
