//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifa
    {
        public string codigo { get; set; }
        public string hasta01 { get; set; }
        public string tarifa01 { get; set; }
        public string hasta02 { get; set; }
        public string tarifa02 { get; set; }
        public string hasta03 { get; set; }
        public string tarifa03 { get; set; }
        public string hasta04 { get; set; }
        public string tarifa04 { get; set; }
        public string hasta05 { get; set; }
        public string tarifa05 { get; set; }
        public string hasta06 { get; set; }
        public string tarifa06 { get; set; }
        public string hasta07 { get; set; }
        public string tarifa07 { get; set; }
        public string hasta08 { get; set; }
        public string tarifa08 { get; set; }
        public string hasta09 { get; set; }
        public string tarifa09 { get; set; }
        public string hasta10 { get; set; }
        public string tarifa10 { get; set; }
        public string hasta11 { get; set; }
        public string tarifa11 { get; set; }
        public string hasta12 { get; set; }
        public string tarifa12 { get; set; }
        public string hasta13 { get; set; }
        public string tarifa13 { get; set; }
        public string hasta14 { get; set; }
        public string tarifa14 { get; set; }
        public string hasta15 { get; set; }
        public string tarifa15 { get; set; }
        public string comis01 { get; set; }
        public string comis02 { get; set; }
        public string comis03 { get; set; }
        public string comis04 { get; set; }
        public string comis05 { get; set; }
        public string comis06 { get; set; }
        public string comis07 { get; set; }
        public string comis08 { get; set; }
        public string comis09 { get; set; }
        public string comis10 { get; set; }
        public string comis11 { get; set; }
        public string comis12 { get; set; }
        public string comis13 { get; set; }
        public string comis14 { get; set; }
        public string comis15 { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
