//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifasnac
    {
        public string moneda { get; set; }
        public int hasta { get; set; }
        public string clienteporcen { get; set; }
        public string clientemin { get; set; }
        public string clientefijo { get; set; }
        public string comioriporcen { get; set; }
        public string comiorimin { get; set; }
        public string comiorifijo { get; set; }
        public string comidesporcen { get; set; }
        public string comidesmin { get; set; }
        public string comidesfijo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
    }
}
