//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticambio
    {
        public string moneda { get; set; }
        public System.DateTime fechac { get; set; }
        public string compra { get; set; }
        public string venta { get; set; }
        public string compracom { get; set; }
        public string spotcom { get; set; }
        public string spotven { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string lotecon { get; set; }
        public string moneye { get; set; }
        public string comprasol { get; set; }
        public string ventasol { get; set; }
        public string globodolar { get; set; }
        public string globoeuro { get; set; }
        public string tcccompra { get; set; }
        public string tccventa { get; set; }
        public string tcceuro { get; set; }
        public string historico { get; set; }
        public string referen { get; set; }
        public string espot { get; set; }
    }
}
