//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticambio1
    {
        public string caja { get; set; }
        public string moneda { get; set; }
        public string compra { get; set; }
        public string venta { get; set; }
        public string compracom { get; set; }
        public string spotcom { get; set; }
        public string spotven { get; set; }
        public string comprasol { get; set; }
        public string ventasol { get; set; }
    }
}
