//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class titanlog
    {
        public string giro { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> env_fecha { get; set; }
        public string env_hora { get; set; }
        public string env_usuario { get; set; }
        public string env_lote { get; set; }
        public Nullable<System.DateTime> rec_fecha { get; set; }
        public string rec_hora { get; set; }
        public string rec_usuario { get; set; }
        public string rec_archivo { get; set; }
        public string rec_fechainv { get; set; }
        public string rec_descripcion { get; set; }
        public string rec_observaciones { get; set; }
        public Nullable<System.DateTime> res_fecha { get; set; }
        public string res_hora { get; set; }
        public string res_usuario { get; set; }
        public string res_lote { get; set; }
        public string res_fechares { get; set; }
        public string res_descripcion { get; set; }
        public Nullable<System.DateTime> can_fecha { get; set; }
        public string can_hora { get; set; }
        public string can_usuario { get; set; }
        public string can_cia { get; set; }
        public string can_age { get; set; }
        public string can_forma { get; set; }
        public string can_fechapg { get; set; }
        public string can_horapag { get; set; }
        public string can_importe { get; set; }
        public string can_notas { get; set; }
    }
}
