//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class totalme
    {
        public string ano { get; set; }
        public string mes { get; set; }
        public string cliente { get; set; }
        public Nullable<int> reccanti { get; set; }
        public string recimpor { get; set; }
        public Nullable<int> envcanti { get; set; }
        public string envimpor { get; set; }
        public Nullable<int> nencanti { get; set; }
        public string nenimpor { get; set; }
        public Nullable<int> nrecanti { get; set; }
        public string nreimpor { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string personeria { get; set; }
        public string ocupa { get; set; }
        public string mismocajero { get; set; }
    }
}
