//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel
    {
        public string numero { get; set; }
        public string origen { get; set; }
        public string codigo { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string isal { get; set; }
        public short valor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string comision { get; set; }
        public string observaciones { get; set; }
        public string usuarioin { get; set; }
        public Nullable<System.DateTime> fechain { get; set; }
        public string horain { get; set; }
        public string anulado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string caja { get; set; }
        public string oripa { get; set; }
        public string movim { get; set; }
        public string lotecaja { get; set; }
        public string traliquid { get; set; }
        public string anulcaja { get; set; }
        public string anullote { get; set; }
        public string formulario { get; set; }
        public string lotecon { get; set; }
        public string nacion1 { get; set; }
        public string nacion2 { get; set; }
        public string operacon { get; set; }
        public string comisionn { get; set; }
        public string igvcomis { get; set; }
        public string loteanu { get; set; }
    }
}
