//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class trf
    {
        public string numero { get; set; }
        public string entidad { get; set; }
        public Nullable<System.DateTime> fechaop { get; set; }
        public string importe { get; set; }
        public string tarifa { get; set; }
        public string cuenta { get; set; }
        public string beneficiario { get; set; }
        public string direccion { get; set; }
        public string bcofinal { get; set; }
        public string dirbco { get; set; }
        public string cuentabco { get; set; }
        public string aba { get; set; }
        public string further { get; set; }
        public string bcointerm { get; set; }
        public string bcoincta { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fechainc { get; set; }
        public string horainc { get; set; }
        public string movimcar { get; set; }
        public string movimbco { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string lotecon { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
