//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class unica
    {
        public int operacion { get; set; }
        public string numero { get; set; }
        public string cliente { get; set; }
        public string importe { get; set; }
        public string bennombre { get; set; }
        public string bendirecc { get; set; }
        public string bendocum { get; set; }
        public string bennumero { get; set; }
        public string ordnombre { get; set; }
        public string orddirecc { get; set; }
        public string orddocum { get; set; }
        public string ordnumero { get; set; }
        public string reanombre { get; set; }
        public string readirecc { get; set; }
        public string readocum { get; set; }
        public string reanumero { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public string usuario { get; set; }
        public string cajero { get; set; }
        public string agencia { get; set; }
    }
}
