//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilidade
    {
        public string codigo { get; set; }
        public string ano { get; set; }
        public string distribuye { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string totaldias { get; set; }
        public string faltas { get; set; }
        public string diasneto { get; set; }
        public string con1 { get; set; }
        public string con2 { get; set; }
        public string con3 { get; set; }
        public string con4 { get; set; }
        public string con5 { get; set; }
        public string con6 { get; set; }
        public string con7 { get; set; }
        public string con8 { get; set; }
        public string con9 { get; set; }
        public string gan1 { get; set; }
        public string gan2 { get; set; }
        public string gan3 { get; set; }
        public string gan4 { get; set; }
        public string gan5 { get; set; }
        public string gan6 { get; set; }
        public string gan7 { get; set; }
        public string gan8 { get; set; }
        public string gan9 { get; set; }
        public string utildias { get; set; }
        public string utilremu { get; set; }
        public string fechapago { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string con10 { get; set; }
        public string gan10 { get; set; }
        public string con11 { get; set; }
        public string gan11 { get; set; }
        public string con12 { get; set; }
        public string gan12 { get; set; }
    }
}
