//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacacione
    {
        public string codigo { get; set; }
        public string periodo { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> desde1 { get; set; }
        public Nullable<System.DateTime> hasta1 { get; set; }
        public string tipo1 { get; set; }
        public string pagada1 { get; set; }
        public Nullable<System.DateTime> desde2 { get; set; }
        public Nullable<System.DateTime> hasta2 { get; set; }
        public string tipo2 { get; set; }
        public string pagada2 { get; set; }
        public Nullable<System.DateTime> desde3 { get; set; }
        public Nullable<System.DateTime> hasta3 { get; set; }
        public string tipo3 { get; set; }
        public string pagada3 { get; set; }
        public Nullable<System.DateTime> desde4 { get; set; }
        public Nullable<System.DateTime> hasta4 { get; set; }
        public string tipo4 { get; set; }
        public string pagada4 { get; set; }
        public string observaciones { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> desde5 { get; set; }
        public Nullable<System.DateTime> hasta5 { get; set; }
        public string tipo5 { get; set; }
        public string pagada5 { get; set; }
        public Nullable<System.DateTime> desde6 { get; set; }
        public Nullable<System.DateTime> hasta6 { get; set; }
        public string tipo6 { get; set; }
        public string pagada6 { get; set; }
        public Nullable<System.DateTime> desde7 { get; set; }
        public Nullable<System.DateTime> hasta7 { get; set; }
        public string tipo7 { get; set; }
        public string pagada7 { get; set; }
        public Nullable<System.DateTime> desde8 { get; set; }
        public Nullable<System.DateTime> hasta8 { get; set; }
        public string tipo8 { get; set; }
        public string pagada8 { get; set; }
    }
}
