//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class valormn
    {
        public System.DateTime fecha { get; set; }
        public string soles { get; set; }
        public string dolares { get; set; }
        public string ingresos { get; set; }
        public string egresos { get; set; }
        public string precio { get; set; }
        public string compra { get; set; }
        public string venta { get; set; }
    }
}
