//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEX.CustomerPayment.Presentation.ReferenceNumerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://peruexpress.cloud/ws_moneygram_dev/soap.php?servicio=MoneyGram_ReferenceNu" +
        "mber", ConfigurationName="ReferenceNumerServiceReference.MoneyGram_ReferenceNumberPort")]
    public interface MoneyGram_ReferenceNumberPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peruexpress.cloud/ws_moneygram_dev/soap.php?servicio=MoneyGram_ReferenceNu" +
            "mber#referenceNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string referenceNumber(string agentID, string agentSequence, string token, [System.ServiceModel.MessageParameterAttribute(Name="referenceNumber")] string referenceNumber1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://peruexpress.cloud/ws_moneygram_dev/soap.php?servicio=MoneyGram_ReferenceNu" +
            "mber#referenceNumber", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> referenceNumberAsync(string agentID, string agentSequence, string token, string referenceNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MoneyGram_ReferenceNumberPortChannel : PEX.CustomerPayment.Presentation.ReferenceNumerServiceReference.MoneyGram_ReferenceNumberPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoneyGram_ReferenceNumberPortClient : System.ServiceModel.ClientBase<PEX.CustomerPayment.Presentation.ReferenceNumerServiceReference.MoneyGram_ReferenceNumberPort>, PEX.CustomerPayment.Presentation.ReferenceNumerServiceReference.MoneyGram_ReferenceNumberPort {
        
        public MoneyGram_ReferenceNumberPortClient() {
        }
        
        public MoneyGram_ReferenceNumberPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoneyGram_ReferenceNumberPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyGram_ReferenceNumberPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyGram_ReferenceNumberPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string referenceNumber(string agentID, string agentSequence, string token, string referenceNumber1) {
            return base.Channel.referenceNumber(agentID, agentSequence, token, referenceNumber1);
        }
        
        public System.Threading.Tasks.Task<string> referenceNumberAsync(string agentID, string agentSequence, string token, string referenceNumber) {
            return base.Channel.referenceNumberAsync(agentID, agentSequence, token, referenceNumber);
        }
    }
}
